version: '2.3'

services:
  display-zenodo:
    image: wordpress
    links:
      - mariadb:mysql
    environment:
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DEBUG=1
    ports:
      - 8083:80
    volumes:
      - .:/var/www/html/wp-content/plugins/display-your-zenodo-community

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress